/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piiiutscuaca.view;

import com.sun.org.apache.bcel.internal.generic.RETURN;
import javax.swing.JOptionPane;

/**
 *
 * @author hahn
 */
public class FrmCuaca extends javax.swing.JFrame {

    /**
     * Creates new form FrmCuaca
     */
    public FrmCuaca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblkota = new javax.swing.JLabel();
        cbHari = new javax.swing.JComboBox();
        label1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblSuhumax = new javax.swing.JLabel();
        lblSuhumin = new javax.swing.JLabel();
        lblKecangin = new javax.swing.JLabel();
        lblLembap = new javax.swing.JLabel();
        lblUdara = new javax.swing.JLabel();
        lblHari = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        DlgHelp1 = new javax.swing.JMenu();
        DlgHelp = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Kota");

        txtKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKotaActionPerformed(evt);
            }
        });

        lblkota.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblkota.setText("Monitor Cuaca");

        cbHari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari Ini", "Besok", "Kemarin", " ", " " }));
        cbHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHariActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label1.setText("Suhu Maksimum");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kecepatan Angin");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Suhu Minimum");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tekanan Udara");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Kelembapan");

        lblHasil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piiiutscuaca/res/04n.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel10.setText("broken clouds");

        lblHari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHari.setText("HARI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblHari, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                            .addGap(28, 28, 28))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(57, 57, 57)
                                            .addComponent(jLabel9))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(41, 41, 41)
                                            .addComponent(jLabel10)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblkota, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKecangin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLembap, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUdara, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSuhumin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSuhumax, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblkota))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSuhumax, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addComponent(lblSuhumin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKecangin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLembap, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUdara, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(88, 88, 88))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblHari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        DlgHelp1.setText("Help");

        DlgHelp.setText("Help");
        DlgHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DlgHelpActionPerformed(evt);
            }
        });
        DlgHelp1.add(DlgHelp);

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        DlgHelp1.add(menuAbout);

        jMenuBar1.add(DlgHelp1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKotaActionPerformed
        // TODO add your handling code here:
        String Hari = (String) cbHari.getSelectedItem();
        lblHari.setText(Hari);
        if (txtKota.getText().equals("Bandung")&& cbHari.getSelectedItem().equals("Hari Ini")){
            lblkota.setText("Bandung");
            lblHari.setText("Hari Ini");
            lblHasil.setText("20.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("30.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("15.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("20.0 m/s");
            lblLembap.setText("180.5 %");
            lblUdara.setText("200.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
        }
        else{
            if (txtKota.getText().equals("Bandung")&& cbHari.getSelectedItem().equals("Besok")){
            lblkota.setText("Bandung");
            lblHari.setText("Besok");
            lblHasil.setText("22.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("32.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("17.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("22.0 m/s");
            lblLembap.setText("200.5 %");
            lblUdara.setText("202.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
        else{
            if (txtKota.getText().equals("Bandung")&& cbHari.getSelectedItem().equals("Kemarin")){
            lblkota.setText("Bandung");
            lblHari.setText("Kemarin");
            lblHasil.setText("24.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("32.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("20.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("22.0 m/s");
            lblLembap.setText("200.5 %");
            lblUdara.setText("202.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
            
         if (txtKota.getText().equals("Jakarta")&& cbHari.getSelectedItem().equals("Hari Ini")){
            lblkota.setText("Jakarta");
            lblHari.setText("Hari Ini");
            lblHasil.setText("26.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("34.0" + (char) 0x00B0 + "C" );
            lblSuhumin.setText("10.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("20.0 m/s");
            lblLembap.setText("200.5 %");
            lblUdara.setText("210.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
        }
        else{
            if (txtKota.getText().equals("Jakarta")&& cbHari.getSelectedItem().equals("Besok")){
            lblkota.setText("Jakarta");
            lblHari.setText("Besok");
            lblHasil.setText("24.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("28.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("20.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("18.0 m/s");
            lblLembap.setText("205.5 %");
            lblUdara.setText("200.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
        else{
            if (txtKota.getText().equals("Jakarta")&& cbHari.getSelectedItem().equals("Kemarin")){
            lblkota.setText("Jakarta");
            lblHari.setText("Kemarin");
            lblHasil.setText("28.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("32.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("24.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("22.0 m/s");
            lblLembap.setText("202.5 %");
            lblUdara.setText("204.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
        else{
            if (txtKota.getText().equals("Surabaya")&& cbHari.getSelectedItem().equals("Hari Ini")){
            lblkota.setText("Surabaya");
            lblHari.setText("Hari Ini");
            lblHasil.setText("30.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("36.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("24.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
        else{
            if (txtKota.getText().equals("Surabaya")&& cbHari.getSelectedItem().equals("Besok")){
            lblkota.setText("Surabaya");
            lblHari.setText("Besok");
            lblHasil.setText("28.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("34.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("22.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("20.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
         else{
            if (txtKota.getText().equals("Surabaya")&& cbHari.getSelectedItem().equals("Kemarin")){
            lblkota.setText("Surabaya");
            lblHari.setText("Kemarin");
            lblHasil.setText("31.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("37.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("25.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
         else{
            if (txtKota.getText().equals("Malang")&& cbHari.getSelectedItem().equals("Hari Ini")){
            lblkota.setText("Malang");
            lblHari.setText("Hari Ini");
            lblHasil.setText("24.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("26.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("18.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }      
         else{
            if (txtKota.getText().equals("Malang")&& cbHari.getSelectedItem().equals("Besok")){
            lblkota.setText("Malang");
            lblHari.setText("Besok");
            lblHasil.setText("22.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("24.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("18.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }  
         else{
            if (txtKota.getText().equals("Malang")&& cbHari.getSelectedItem().equals("Kemarin")){
            lblkota.setText("Malang");
            lblHari.setText("Kemarin");
            lblHasil.setText("26.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("28.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("24.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }      
        else{
                JOptionPane.showMessageDialog(null, "Kota " + txtKota.getText() + " Belum ditemukan");
            }
        
        
            
    }                                      
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }//GEN-LAST:event_txtKotaActionPerformed
    
    private void cbHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHariActionPerformed
        // TODO add your handling code here:
        String Hari = (String) cbHari.getSelectedItem();
        lblHari.setText(Hari);
        if (txtKota.getText().equals("Bandung")&& cbHari.getSelectedItem().equals("Hari Ini")){
            lblkota.setText("Bandung");
            lblHari.setText("Hari Ini");
            lblHasil.setText("20.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("30.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("15.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("20.0 m/s");
            lblLembap.setText("180.5 %");
            lblUdara.setText("200.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
        }
        else{
            if (txtKota.getText().equals("Bandung")&& cbHari.getSelectedItem().equals("Besok")){
            lblkota.setText("Bandung");
            lblHari.setText("Besok");
            lblHasil.setText("22.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("32.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("17.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("22.0 m/s");
            lblLembap.setText("200.5 %");
            lblUdara.setText("202.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
        else{
            if (txtKota.getText().equals("Bandung")&& cbHari.getSelectedItem().equals("Kemarin")){
            lblkota.setText("Bandung");
            lblHari.setText("Kemarin");
            lblHasil.setText("24.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("32.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("20.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("22.0 m/s");
            lblLembap.setText("200.5 %");
            lblUdara.setText("202.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
            
         if (txtKota.getText().equals("Jakarta")&& cbHari.getSelectedItem().equals("Hari Ini")){
            lblkota.setText("Jakarta");
            lblHari.setText("Hari Ini");
            lblHasil.setText("26.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("34.0" + (char) 0x00B0 + "C" );
            lblSuhumin.setText("10.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("20.0 m/s");
            lblLembap.setText("200.5 %");
            lblUdara.setText("210.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
        }
        else{
            if (txtKota.getText().equals("Jakarta")&& cbHari.getSelectedItem().equals("Besok")){
            lblkota.setText("Jakarta");
            lblHari.setText("Besok");
            lblHasil.setText("24.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("28.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("20.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("18.0 m/s");
            lblLembap.setText("205.5 %");
            lblUdara.setText("200.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
        else{
            if (txtKota.getText().equals("Jakarta")&& cbHari.getSelectedItem().equals("Kemarin")){
            lblkota.setText("Jakarta");
            lblHari.setText("Kemarin");
            lblHasil.setText("28.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("32.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("24.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("22.0 m/s");
            lblLembap.setText("202.5 %");
            lblUdara.setText("204.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
        else{
            if (txtKota.getText().equals("Surabaya")&& cbHari.getSelectedItem().equals("Hari Ini")){
            lblkota.setText("Surabaya");
            lblHari.setText("Hari Ini");
            lblHasil.setText("30.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("36.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("24.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
        else{
            if (txtKota.getText().equals("Surabaya")&& cbHari.getSelectedItem().equals("Besok")){
            lblkota.setText("Surabaya");
            lblHari.setText("Besok");
            lblHasil.setText("28.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("34.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("22.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("20.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
         else{
            if (txtKota.getText().equals("Surabaya")&& cbHari.getSelectedItem().equals("Kemarin")){
            lblkota.setText("Surabaya");
            lblHari.setText("Kemarin");
            lblHasil.setText("31.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("37.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("25.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }
         else{
            if (txtKota.getText().equals("Malang")&& cbHari.getSelectedItem().equals("Hari Ini")){
            lblkota.setText("Malang");
            lblHari.setText("Hari Ini");
            lblHasil.setText("24.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("26.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("18.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }      
         else{
            if (txtKota.getText().equals("Malang")&& cbHari.getSelectedItem().equals("Besok")){
            lblkota.setText("Malang");
            lblHari.setText("Besok");
            lblHasil.setText("22.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("24.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("18.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }  
         else{
            if (txtKota.getText().equals("Malang")&& cbHari.getSelectedItem().equals("Kemarin")){
            lblkota.setText("Malang");
            lblHari.setText("Kemarin");
            lblHasil.setText("26.5" + (char) 0x00B0 + "C");
            lblSuhumax.setText("28.0" + (char) 0x00B0 + "C");
            lblSuhumin.setText("24.0" + (char) 0x00B0 + "C");
            lblKecangin.setText("25.0 m/s");
            lblLembap.setText("206.5 %");
            lblUdara.setText("201.2 hPa");
            lblSuhumax.setEnabled(false);
            lblSuhumin.setEnabled(false);
            lblKecangin.setEnabled(false);
            lblLembap.setEnabled(false);
            lblUdara.setEnabled(false);
            }      
        else{
                JOptionPane.showMessageDialog(null, "Kota " + txtKota.getText() + " Belum ditemukan");
            }
        
        
            
    }//GEN-LAST:event_cbHariActionPerformed
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
        private void DlgHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DlgHelpActionPerformed
            // TODO add your handling code here:
            DlgHelp help = new DlgHelp();
        help.setVisible(true);
        }//GEN-LAST:event_DlgHelpActionPerformed

        private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
            // TODO add your handling code here:
            JOptionPane.showMessageDialog(null, "Uts Java 3 - Dimas Anjasmara - 1641803");
        }//GEN-LAST:event_menuAboutActionPerformed
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCuaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DlgHelp;
    private javax.swing.JMenu DlgHelp1;
    private javax.swing.JComboBox cbHari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lblHari;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblKecangin;
    private javax.swing.JLabel lblLembap;
    private javax.swing.JLabel lblSuhumax;
    private javax.swing.JLabel lblSuhumin;
    private javax.swing.JLabel lblUdara;
    private javax.swing.JLabel lblkota;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JTextField txtKota;
    // End of variables declaration//GEN-END:variables
}
